const data = [
  {
    _id: "5a73c5aa6959a655ea649cdb",
    gymName: "부평 더블유짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/161543c22ff45b4645/4K6uVdbJnWndJAmYHdfhiJGFKMyGznaShXc7ckxGwPma.jpg",
    address: "인천 부평구 부평동",
    location: [126.722819, 37.492248],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["헬스", "스피닝", "그룹P.T"],
    program: {
      free: "O.T (3개월 등록시 1회 / 6개월 등록시 2회)",
    },
    service: {
      free: "주차 (2시간 - SUV/외제차는 제외)",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: true,
      lowestPrice: 324000,
      originalPrice: 349200,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: 9,
    },
    review: {
      rate: 4.55,
      count: 23,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "62ecab03f9efad001d90bc08",
    gymName: "부평 3세트짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1826c7c068238e39cb/4K8gHar7QpSvsgqithgk5hmGY5XPXTA7K9eCznKvozxx.jpg",
    address: "인천 부평구 부평동",
    location: [126.72501085916447, 37.49093683468285],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["P.T", "헬스"],
    program: {
      free: "기간 선택에 따른 횟수 안내 / 1개월 8회 / 3개월 24회 / 6개월 48회 / 12개월 96회",
    },
    service: {
      free: "락커 / 운동복 / 주차 2시간 가능",
    },
    price: {
      name: "1:1(30분 집중)PT",
      count: 40,
      isLowestPrice: true,
      lowestPrice: 1100000,
      originalPrice: 1150000,
      period: null,
      priceType: "count",
      itemTags: [],
      lowestPriceRemainingCount: 1,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "61936a38e271c900398564e1",
    gymName: "부평 PT의정석 운동재활센터",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17d27d6ecb9117de10/4K7y1LZk6uGHeY8uKFvvoerx8vAzcMhZhj9HHeW8fBgt.jpg",
    address: "인천 부평구 부평동",
    location: [126.72394228220516, 37.49672824822733],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["P.T"],
    program: {
      free: "",
    },
    service: {
      free: "수건 / 락커 / Wi-fi",
    },
    price: {
      name: "1:1 P.T (횟수제)",
      count: null,
      isLowestPrice: false,
      lowestPrice: 690000,
      originalPrice: 690000,
      period: 1,
      priceType: "period",
      itemTags: [],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "64d0d308d7c1bd001d65b785",
    gymName: "부평 키워드핏",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/189cfb859c73854ec6/2WQemZ31hyjcNCtCMSpqjQvFPBsakJxSXmp3.list_photo.jpg",
    address: "인천 부평구 부평동",
    location: [126.7217453, 37.4977424],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "수건 / 락커",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 399000,
      originalPrice: 399000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "65ee9ca2b2e9a2001dc1f7e3",
    gymName: "부평남부 바디홀릭 필라테스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18e2c13da7355cff1/2ZwYTEgcGbZ7qNpRvcZ4bBEQvCRn7CCmFdff.센터 Small 복사.jpg",
    address: "인천 부평구 부평동",
    location: [126.72463962670848, 37.48733420227458],
    isWomenOnly: false,
    isReservationRequired: true,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["필라테스"],
    program: {
      free: "",
    },
    service: {
      free: "️수건/ 샤워시설 / 반신욕기 / ️공용락커",
    },
    price: {
      name: "6:1 필라테스",
      count: 120,
      isLowestPrice: false,
      lowestPrice: 1160000,
      originalPrice: 1160000,
      period: null,
      priceType: "count",
      itemTags: ["필라테스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "6386b97eb54b10001dec4fe3",
    gymName: "부평 mgym",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/184c64497a13d462cd/NV8xnm3W7Lz91cpfB6BB5qKjzHUe7Ws1PP.list_photo.jpg",
    address: "인천 부평구 부평동",
    location: [126.72965251611235, 37.49880655738467],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "O.T",
    },
    service: {
      free: "주차 (2시간)",
    },
    price: {
      name: "헬스",
      count: null,
      isLowestPrice: false,
      lowestPrice: 396000,
      originalPrice: 396000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "6183671e6bdf97003910046b",
    gymName: "산곡 플랜A피트니스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ce94ad08d5c34447/4K7xr2p8vPEYxHxpJnCkzgQfgoA1CHrTYzpizPBjPa24.jpg",
    address: "인천 부평구 산곡동",
    location: [126.71299418004969, 37.50214891920522],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "탁구", "스쿼시"],
    program: {
      free: "",
    },
    service: {
      free: "주차 150분 / Wi-fi",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 396000,
      originalPrice: 396000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 5,
      count: 5,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "636b0d23d6679f001d132deb",
    gymName: "부평 PT시작",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1845a2b539e5f19578/4K8ggnJZ5AD7w3khCU7XVtjhLAGinLX5NPdxT2qVqVpU.jpg",
    address: "인천 부평구 부평동",
    location: [126.72103519839345, 37.50489982808945],
    isWomenOnly: false,
    isReservationRequired: true,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["P.T"],
    program: {
      free: "",
    },
    service: {
      free: "운동복 / 개인락커 / 커피이용",
    },
    price: {
      name: "1:1 PT",
      count: 50,
      isLowestPrice: false,
      lowestPrice: 2750000,
      originalPrice: 2750000,
      period: null,
      priceType: "count",
      itemTags: ["P.T"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 5,
      count: 1,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "61837da96bdf9700391007f7",
    gymName: "부평구청 타임짐휘트니스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17ce9a2dc2f2ea44fe/4K7xr2pEyhVMzEc5bz6PhzPHh3kDe3k4dKF83PPF9UTZ.jpg",
    address: "인천 부평구 부평동",
    location: [126.719892, 37.505882],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "가변주차가능 / 샤워시설 / WI-FI",
    },
    price: {
      name: "헬스 이용권",
      count: null,
      isLowestPrice: true,
      lowestPrice: 359000,
      originalPrice: 360000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: 7,
    },
    review: {
      rate: 5,
      count: 3,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "60c0a19ac70b9e003995a855",
    gymName: "부개 팀타이거복싱짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/179f0774361ef22f2/kXYbCnxsTYFHiFCvUChrcYKP1MrhMobhTw2sqAaWLQ.jpg",
    address: "인천 부평구 부개동",
    location: [126.73551054447834, 37.497418727855234],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["복싱"],
    program: {
      free: "G.X (20시)",
    },
    service: {
      free: "Wi-fi / 수건 / 락커",
    },
    price: {
      name: "복싱",
      count: null,
      isLowestPrice: false,
      lowestPrice: 1050000,
      originalPrice: 1050000,
      period: 12,
      priceType: "period",
      itemTags: ["복싱"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "615e6c826bdf9700390c9e95",
    gymName: "부개 골드짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/17c58d7dcf52f4d98d/4K7xorRJgwgywmRHpZMi7K7cwoVQDFHobqagY4tZmiBi.jpg",
    address: "인천 부평구 부개동",
    location: [126.73837978862596, 37.493667442301806],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "",
    },
    price: {
      name: "헬스",
      count: null,
      isLowestPrice: false,
      lowestPrice: 350000,
      originalPrice: 350000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 5,
      count: 1,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "637c6f2be38504001de06524",
    gymName: "부개 복싱인사이드짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1849e12404f415c4a3/MCvy7chq1vAp8KtHAd7DZ37mebt5DzVPd8.list_photo.jpg",
    address: "인천 부평구 부개동",
    location: [126.73794680242598, 37.49738364133078],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["복싱"],
    program: {
      free: "",
    },
    service: {
      free: "",
    },
    price: {
      name: "평일기간권(주5회)",
      count: null,
      isLowestPrice: true,
      lowestPrice: 1395000,
      originalPrice: 1455000,
      period: 12,
      priceType: "period",
      itemTags: ["복싱"],
      lowestPriceRemainingCount: 10,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "62a6c095123b8b001d5372bb",
    gymName: "부개 유알짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/1815b6048d82eaa98f/2kbWgJMh73NPGoMP7Pc7tpU6EukEBEPzx5x7.list_photo.jpg",
    address: "인천 부평구 부개동",
    location: [126.73429263915732, 37.504191570220534],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "30회 PT 등록시! 회원복 & 락커 제공! / 수건 무료 제공 / 일일 입장제한 X / 등록시 무료 피티 1회 제공",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 396000,
      originalPrice: 396000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 5,
      count: 4,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "607e39c0c70b9e0039942978",
    gymName: "일신 엘케이짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/178ed1197661950cf3/4K7pEJtywheyiTpxFR77dyrYXAUzUyZ2H6ZF7KydMs6g.jpg",
    address: "인천 부평구 일신동",
    location: [126.74234310156417, 37.48623588383842],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "O.T (상시지도)",
    },
    service: {
      free: "수건 / 운동복 / 체성분 분석 / Wi-fi / 주차(18시 이후 무료주차)",
    },
    price: {
      name: "헬스+운동복",
      count: null,
      isLowestPrice: true,
      lowestPrice: 329000,
      originalPrice: 363000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: 8,
    },
    review: {
      rate: 5,
      count: 2,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "59f61259b0993a41223b764d",
    gymName: "삼산 테크노짐",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/15f6937ac63467f188/Small)TechnoGym.jpg",
    address: "인천 부평구 삼산동",
    location: [126.735858, 37.507097],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["헬스"],
    program: {
      free: "-G.X [파워덤벨 / 코어트레이닝 / 요가 / 댄스에어로빅 / 전신스트레칭 / S-라인체조] / / O.T 1회 (*간단한 기구설명 및 동기부여)",
    },
    service: {
      free: "주차 3시간 / 인바디 측정",
    },
    price: {
      name: "헬스+G.X [부부관장님이 직접진행하는 티칭 그룹수업]",
      count: null,
      isLowestPrice: true,
      lowestPrice: 501000,
      originalPrice: 505000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: 10,
    },
    review: {
      rate: 5,
      count: 14,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "6286411618d341001d0b01dc",
    gymName: "부개 바디패션짐 본점 24시",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/180dc6e41623842c1/kXjoYTf8yjZtEqBum7mBuLWhMTpies1cq14XPmrQDN.jpg",
    address: "인천 부평구 부개동",
    location: [126.73964833296745, 37.50401428488515],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "O.T 1회(선택사항)",
    },
    service: {
      free: "",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: true,
      lowestPrice: 249000,
      originalPrice: 250000,
      period: 12,
      priceType: "period",
      itemTags: [],
      lowestPriceRemainingCount: 5,
    },
    review: {
      rate: 4.15,
      count: 10,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "5a16bfd5e3426a253d9ae1a1",
    gymName: "갈산 팀복싱짐 휘트니스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/15fe8dd5b822a4e411/2WiqieFqx2qPG7iUQeT5S89RL6ZoyawaKHYH.list_photo.jpg",
    address: "인천 부평구 갈산동",
    location: [126.725725, 37.511593],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: true,
    exhibitionRemainingCount: null,
    tags: ["복싱", "헬스"],
    program: {
      free: "/",
    },
    service: {
      free: "운동복 / 수건 /",
    },
    price: {
      name: "헬스",
      count: null,
      isLowestPrice: false,
      lowestPrice: 360000,
      originalPrice: 360000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 4.88,
      count: 2,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "6478433bf3cbba001d5f4f55",
    gymName: "부평 노력의천재 헬스&PT",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/18875c6a0c120fe43/kXkA9EVriGUYZArwZQn5eXDnp9mPDznf4Rbs3HXMkt.jpg",
    address: "인천 부평구 갈산동",
    location: [126.72356183533834, 37.515925019863396],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "️수건",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 400000,
      originalPrice: 400000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 0,
      count: 0,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "62783b62421e32001d56895d",
    gymName: "동암 다짐 휘트니스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/180a5a7f9ed5435d3/kXjoWZfXJdZNRYGbXr9CPifAqoxGfeDwsEHRjcwzde.jpg",
    address: "인천 부평구 십정동",
    location: [126.70053992247362, 37.47286849040199],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: false,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "OT",
    },
    service: {
      free: "수건 / 주차",
    },
    price: {
      name: "헬스 회원권+운동복",
      count: null,
      isLowestPrice: false,
      lowestPrice: 200000,
      originalPrice: 200000,
      period: 6,
      priceType: "period",
      itemTags: [],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 4.67,
      count: 9,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
  {
    _id: "62e7726ff9efad001d8e579b",
    gymName: "갈산 고바디 피트니스",
    gymPhotoBig: null,
    gymPhotoSmall:
      "https://s3.ap-northeast-2.amazonaws.com/stone-i-dagym-centers/images/gyms/182581702b9321a8ed/4K8gHXmjHsg3PCGKpjqdpNiBh9WZGPoGgDS1XVbPpb2x.jpg",
    address: "인천 부평구 청천동",
    location: [126.72096443314094, 37.51707444582458],
    isWomenOnly: false,
    isReservationRequired: false,
    hasDailyItem: true,
    isLiked: null,
    isLowestPrice: false,
    exhibitionRemainingCount: null,
    tags: ["헬스", "P.T"],
    program: {
      free: "",
    },
    service: {
      free: "Wi-fi / 주차장 / 수건",
    },
    price: {
      name: "헬스 회원권",
      count: null,
      isLowestPrice: false,
      lowestPrice: 600000,
      originalPrice: 600000,
      period: 12,
      priceType: "period",
      itemTags: ["헬스"],
      lowestPriceRemainingCount: null,
    },
    review: {
      rate: 4.67,
      count: 3,
    },
    videoUrl: null,
    videoThumbnailUrl: null,
  },
];

const newData = data.map((v) => ({
  gymName: v.gymName,
  address: v.address,
  photoSmall: v.gymPhotoSmall,
}));

newData.forEach((v) => {
  const img = document.createElement("img");
  img.src = v.photoSmall;
  const h2 = document.createElement("h2");
  h2.innerText = v.gymName;
  const h4 = document.createElement("h4");
  h4.innerText = v.address;
  const box = document.createElement("div");
  box.appendChild(img);
  box.appendChild(h2);
  box.appendChild(h4);
  const container = document.querySelector(".container");
  container.appendChild(box);
});
